const cat = {
  tvAndAudio: "tvAndAudio",
  tvBox: "tvBox",
  powerTools: "powerTools",
  headphones: "headphones",
  cellPhones: "cellPhones",
  smartWatches: "smartWatches",
  gameAndVideo: "gameAndVideo",
  robotClean: "robotClean",
  sportWatches: "sportWatches",
  tablets: "tablets",
  computersAndLaptop: "computersAndLaptop",
  camerasAndPhotos: "camerasAndPhotos",
  homeAppliances: "homeAppliances",
  accessories: "accessories",
  wearables: "wearables",
};

export const categories = [
  {
    _id: 1001,
    name: "TV & Audio",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400",
    description:
      "High-quality televisions, sound systems, and audio equipment for your entertainment needs.",
    _base: "tvAndAudio",
  },
  {
    _id: 1002,
    name: "TV Box",
    image: "https://images.unsplash.com/photo-1593078165821-3c8bc0d9b9d0?w=400",
    description:
      "Smart streaming devices and TV boxes for unlimited entertainment options.",
    _base: "tvBox",
  },
  {
    _id: 1003,
    name: "Power Tools",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400",
    description:
      "Professional-grade power tools for construction and DIY projects.",
    _base: "powerTools",
  },
  {
    _id: 1004,
    name: "Headphones",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
    description:
      "Premium headphones and earbuds for immersive audio experiences.",
    _base: "headphones",
  },
  {
    _id: 1005,
    name: "Cell Phones",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400",
    description:
      "Latest smartphones with cutting-edge technology and features.",
    _base: "cellPhones",
  },
  {
    _id: 1006,
    name: "Smart Watches",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
    description: "Advanced smartwatches for health tracking and connectivity.",
    _base: "smartWatches",
  },
  {
    _id: 1007,
    name: "Game & Video",
    image: "https://images.unsplash.com/photo-1486401899868-0e435ed85128?w=400",
    description: "Gaming consoles, controllers, and video game accessories.",
    _base: "gameAndVideo",
  },
  {
    _id: 1008,
    name: "Robot Clean",
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400",
    description: "Automated cleaning solutions for modern smart homes.",
    _base: "robotClean",
  },
  {
    _id: 1009,
    name: "Sport Watches",
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400",
    description: "Fitness trackers and sport watches for active lifestyles.",
    _base: "sportWatches",
  },
  {
    _id: 1010,
    name: "Tablets",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
    description: "Portable tablets for work, entertainment, and creativity.",
    _base: "tablets",
  },
  {
    _id: 1011,
    name: "Computers & Laptop",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400",
    description: "High-performance laptops and desktop computers.",
    _base: "computersAndLaptop",
  },
  {
    _id: 1012,
    name: "Cameras & Photos",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400",
    description: "Professional cameras and photography equipment.",
    _base: "camerasAndPhotos",
  },
  {
    _id: 1013,
    name: "Home Appliances",
    image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400",
    description: "Essential home appliances for modern living.",
    _base: "homeAppliances",
  },
  {
    _id: 1014,
    name: "Accessories",
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400",
    description: "Tech accessories and gadgets for all your devices.",
    _base: "accessories",
  },
];

export const highlightsProducts = [
  {
    _id: 3001,
    name: "New Deals at Best Prices",
    title: "From $40.00",
    buttonTitle: "Browse Deals",
    image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800",
    _base: "/product",
    color: "#000000",
  },
  {
    _id: 3002,
    name: "Colorful Redmi Note 6 Pro",
    title: "From $40.00",
    buttonTitle: "Shop Cellphone",
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800",
    _base: "/category/cellPhones",
    color: "#ffffff",
  },
  {
    _id: 3003,
    name: "1000 mAh Power Bank",
    title: "From $40.00",
    buttonTitle: "Shop Now",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800",
    _base: "/product",
    color: "#ffffff",
  },
];

export const blogsData = [
  {
    _id: 4001,
    image: "https://images.unsplash.com/photo-1592286927505-b58b488a385e?w=600",
    title: "iPhone 15 rear camera design will be available",
    _base: "Technology",
    description:
      "The latest iPhone 15 features a revolutionary camera system with advanced computational photography capabilities. Experience stunning image quality with improved low-light performance and enhanced zoom features.",
  },
  {
    _id: 4002,
    image: "https://images.unsplash.com/photo-1545127398-14699f92334b?w=600",
    title: "Setup your surround sound speaker",
    _base: "Smart thing",
    description:
      "Transform your home entertainment experience with our comprehensive guide to setting up surround sound systems. Learn about speaker placement, calibration, and optimization tips.",
  },
  {
    _id: 4003,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600",
    title: "Hook up a receiver for your home theater",
    _base: "Life style",
    description:
      "Create the ultimate home theater experience by properly connecting your AV receiver. Follow our step-by-step guide for optimal audio and video quality.",
  },
];

export const products = [
  {
    _id: 2001,
    name: "Divoom Tivoo Portable Bluetooth Speaker Smart Clock",
    images: [
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500",
      "https://images.unsplash.com/photo-1545127398-14699f92334b?w=500",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500",
    ],
    description:
      "Multifunctional Bluetooth speaker with pixel art display, smart alarm clock features, and customizable LED animations. Control via app for unique home decoration.",
    regularPrice: 600,
    discountedPrice: 580,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "TV & Audio",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Divoom",
    isStock: true,
    overView: "Bluetooth Speaker",
    isNew: true,
    _base: cat?.tvAndAudio,
  },
  {
    _id: 2002,
    name: "Xiaomi Mi Watch Lite GPS Bluetooth Smart Watch",
    images: [
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500",
    ],
    description:
      "Advanced fitness tracking with GPS, heart rate monitor, and 1.4-inch TFTLCD screen. Water resistant up to 5 ATM for swimming and daily activities.",
    regularPrice: 250,
    discountedPrice: 180,
    quantity: 1,
    rating: 4.8,
    reviews: 80,
    category: "Smart Watches",
    colors: ["black", "blue", "pink", "green"],
    brand: "Xiaomi",
    isStock: true,
    overView: "Smart health watch",
    isNew: false,
    _base: cat?.smartWatches,
  },
  {
    _id: 2003,
    name: "M3 Color Screen Smart Sport Bracelet Fitness Tracker",
    images: [
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500",
      "https://images.unsplash.com/photo-1557438159-51eec7a6c9e8?w=500",
    ],
    description:
      "Activity tracking bracelet with heart rate monitoring, step counter, and calorie tracker. Compatible with iOS and Android devices.",
    regularPrice: 650,
    discountedPrice: 570,
    quantity: 1,
    rating: 4.2,
    reviews: 30,
    category: "Sport Watches",
    colors: ["red", "blue", "black"],
    brand: "MI Exclusive",
    isStock: true,
    overView: "Smart health watch",
    isNew: true,
    _base: cat?.sportWatches,
  },
  {
    _id: 2004,
    name: "SJ8 Air 4K Action Camera WIFI Waterproof Sports DV",
    images: [
      "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=500",
      "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=500",
    ],
    description:
      "Ultra HD 4K 60fps action camera with WiFi remote control, waterproof design for extreme sports and underwater photography.",
    regularPrice: 400,
    discountedPrice: 350,
    quantity: 1,
    rating: 4.2,
    reviews: 120,
    category: "Camera & Photos",
    colors: ["black", "silver"],
    brand: "SJ Cam",
    isStock: false,
    overView: "Cameras & Photos",
    isNew: false,
    _base: cat?.camerasAndPhotos,
  },
  {
    _id: 2005,
    name: "Redmi Xiaoai Bluetooth Music Speaker Voice Control",
    images: [
      "https://images.unsplash.com/photo-1589492477829-5e65395b66cc?w=500",
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500",
    ],
    description:
      "Smart Bluetooth 4.2 speaker with voice remote control. Compatible with Android and iPhone for seamless music streaming.",
    regularPrice: 90,
    discountedPrice: 80,
    quantity: 1,
    rating: 4.2,
    reviews: 20,
    category: "TV & Audio",
    colors: ["white", "black", "red"],
    brand: "Xiaomi",
    isStock: true,
    overView: "Bluetooth Speaker",
    isNew: true,
    _base: cat?.tvAndAudio,
  },
  {
    _id: 2006,
    name: "Apple Watch Series 8 GPS Fitness Tracking Smartwatch",
    images: [
      "https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=500",
      "https://images.unsplash.com/photo-1510017803434-a899398421b3?w=500",
    ],
    description:
      "Advanced health monitoring with ECG, blood oxygen sensor, and always-on retina display. Seamless integration with iPhone.",
    regularPrice: 300,
    discountedPrice: 280,
    quantity: 1,
    rating: 4.8,
    reviews: 110,
    category: "Smart Watches",
    colors: ["silver", "gold", "black", "blue"],
    brand: "Apple",
    isStock: true,
    overView: "Smart health watch",
    isNew: false,
    _base: cat.smartWatches,
  },
  {
    _id: 2007,
    name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500",
    ],
    description:
      "Industry-leading noise cancellation with premium sound quality. 30-hour battery life and multipoint connection.",
    regularPrice: 600,
    discountedPrice: 550,
    quantity: 1,
    rating: 4.9,
    reviews: 260,
    category: "Headphones & Speakers",
    colors: ["black", "silver", "blue"],
    brand: "Sony",
    isStock: true,
    overView: "Premium Headphones",
    isNew: true,
    _base: cat.headphones,
  },
  {
    _id: 2008,
    name: "MacBook Pro 14-inch M3 Chip Laptop Computer",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500",
    ],
    description:
      "Powerful M3 chip with 14-core GPU, Liquid Retina XDR display, and up to 18 hours of battery life for professionals.",
    regularPrice: 1100,
    discountedPrice: 1080,
    quantity: 1,
    rating: 4.9,
    reviews: 190,
    category: "Computers & Laptops",
    colors: ["space gray", "silver"],
    brand: "Apple",
    isStock: true,
    overView: "Professional Laptop",
    isNew: false,
    _base: cat?.computersAndLaptop,
  },
  {
    _id: 2009,
    name: "Roborock S8 Pro Ultra Robot Vacuum and Mop",
    images: [
      "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500",
      "https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=500",
    ],
    description:
      "Self-emptying robot vacuum with sonic mopping, 6000Pa suction, and intelligent obstacle avoidance technology.",
    regularPrice: 450,
    discountedPrice: 380,
    quantity: 1,
    rating: 4.7,
    reviews: 70,
    category: "Robot Clean",
    colors: ["white", "black"],
    brand: "Roborock",
    isStock: true,
    overView: "Robot Vacuum",
    isNew: true,
    _base: cat?.robotClean,
  },
  {
    _id: 2010,
    name: "Samsung Galaxy S24 Ultra 5G Smartphone",
    images: [
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500",
    ],
    description:
      "Premium flagship smartphone with 200MP camera, S Pen, and AI-powered features. 6.8-inch Dynamic AMOLED display.",
    regularPrice: 1305,
    discountedPrice: 1285,
    quantity: 1,
    rating: 4.8,
    reviews: 160,
    category: "Cell Phones",
    colors: ["gray", "black", "violet"],
    brand: "Samsung",
    isStock: true,
    overView: "Flagship Smartphone",
    isNew: true,
    _base: cat?.cellPhones,
  },
  {
    _id: 2026,
    name: "iPad Pro 12.9-inch M2 Chip Tablet",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500",
      "https://images.unsplash.com/photo-1585790050230-5dd28404f905?w=500",
    ],
    description:
      "Professional-grade tablet with M2 chip, Liquid Retina XDR display, and Apple Pencil support for creative professionals.",
    regularPrice: 1099,
    discountedPrice: 1049,
    quantity: 1,
    rating: 4.8,
    reviews: 145,
    category: "Tablets",
    colors: ["space gray", "silver"],
    brand: "Apple",
    isStock: true,
    overView: "Pro Tablet",
    isNew: true,
    _base: cat?.tablets,
  },
  {
    _id: 2027,
    name: "PlayStation 5 Console with DualSense Controller",
    images: [
      "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=500",
      "https://images.unsplash.com/photo-1622297845775-5ff3fef71d13?w=500",
    ],
    description:
      "Next-gen gaming console with ultra-high speed SSD, ray tracing, and haptic feedback controller for immersive gameplay.",
    regularPrice: 499,
    discountedPrice: 479,
    quantity: 1,
    rating: 4.9,
    reviews: 320,
    category: "Game and Video",
    colors: ["white", "black"],
    brand: "Sony",
    isStock: true,
    overView: "Gaming Console",
    isNew: true,
    _base: cat?.gameAndVideo,
  },
  {
    _id: 2028,
    name: "Dyson V15 Detect Cordless Vacuum Cleaner",
    images: ["https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500"],
    description:
      "Laser detection technology reveals hidden dust. Powerful suction with intelligent cleaning modes for all floor types.",
    regularPrice: 649,
    discountedPrice: 599,
    quantity: 1,
    rating: 4.7,
    reviews: 88,
    category: "Home Appliances",
    colors: ["nickel", "blue"],
    brand: "Dyson",
    isStock: true,
    overView: "Cordless Vacuum",
    isNew: true,
    _base: "homeAppliances",
  },
  {
    _id: 2029,
    name: "AirPods Pro 2nd Generation with MagSafe Charging",
    images: [
      "https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=500",
      "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=500",
    ],
    description:
      "Advanced active noise cancellation, adaptive transparency, and spatial audio for an immersive listening experience.",
    regularPrice: 249,
    discountedPrice: 229,
    quantity: 1,
    rating: 4.8,
    reviews: 275,
    category: "Headphones",
    colors: ["white"],
    brand: "Apple",
    isStock: true,
    overView: "True Wireless Earbuds",
    isNew: true,
    _base: cat?.headphones,
  },
  {
    _id: 2030,
    name: "Anker PowerCore 20000mAh Portable Charger",
    images: [
      "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=500",
    ],
    description:
      "High-capacity power bank with dual USB ports, fast charging technology, and compact design for travel.",
    regularPrice: 59,
    discountedPrice: 49,
    quantity: 1,
    rating: 4.6,
    reviews: 450,
    category: "Accessories",
    colors: ["black", "white", "blue"],
    brand: "Anker",
    isStock: true,
    overView: "Power Bank",
    isNew: false,
    _base: "accessories",
  },
];
